### ISSUE TITLE
用户登录后 server 无法记录当前 session

### ISSUE THREAD

**Issue by zehaowang983** [sysu-swsad-team/niffler-backend#2]
request.user 为匿名用户，是否是浏览器发送的请求 header 中未包含 cookie 导致
AttributeError: 'AnonymousUser' object has no attribute 'profile'

**Comment by Ernie1** [comment]
感谢您的关注，可能是cookie的域不同导致的。

**Comment by Ernie1** [comment]
现在关闭问题，如果还有任何问题，欢迎再次开启这个issue。
